Staging workflows

diff --git a/.github/workflows/terraform.yaml b/.github/workflows/terraform.yaml
--- a/.github/workflows/terraform.yaml
+++ b/.github/workflows/terraform.yaml
@@ -3,6 +3,60 @@ on:
   push:
     branches:
      - main
+     - iac-stage
     paths:
      - terraform/**
-     
+  pull_request:
+    branches:
+     - main
+    paths:
+      - terraform/**
+
+env: 
+   # Those credentails is essential for access AWS
+   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+   #S3 Bucket for Terraform State (ST)
+   BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
+   AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
+   EKS_CLUSTER: eks-cluster
+
+jobs:
+  terraform:
+    name: "Apply terraform changes"
+    runs-on: ubuntu-latest
+    default:
+      run: 
+        shell: bash
+        working-directory: ./terraform
+
+    steps:
+      - name: checkout source code
+        uses: actions/checkout@v5.0.0
+
+      - name:  HashiCorp - Setup Terraform
+        uses: hashicorp/setup-terraform@v2.0.3
+        #with:
+
+      - name: Terrafrom Init
+        id: init
+        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
+          
+      - name: Terraform Fmt
+        id: fmt
+        run: terraform fmt -check
+
+      - name: Terraform Validate
+        id: validate
+        run: terraform validate
+
+      - name: Terraform Plan
+        id: plan
+        run : terraform plan -no-color -input=false -out planefile
+        continue on error: true
+
+      - name: Terraform Plan Status
+        if: steps.plan.outcome == 'failure'   #outcome is a variable that will actually has the failure or success
+        run: exit 1
+
+  
